on: [push]
name: Lint
jobs:
  lint:
    name: Lint check
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 1
      - name: check
        run: make lint_no_docker
